In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import yfinance  as yf 
import numpy as np 
plt.style.use('fivethirtyeight')

In [7]:
stock_data = yf.download("BTC-USD", period="15y")

[*********************100%***********************]  1 of 1 completed

In [8]:
stock_data.head()

Price            Close        High         Low        Open    Volume
Ticker         BTC-USD     BTC-USD     BTC-USD     BTC-USD   BTC-USD
Date
2014-09-17  457.334015  468.174011  452.421997  465.864014  21056800
2014-09-18  424.440002  456.859985  413.104004  456.859985  34483200
2014-09-19  394.795990  427.834991  384.532013  424.102997  37919700
2014-09-20  408.903992  423.295990  389.882996  394.673004  36863600
2014-09-21  398.821014  412.425995  393.181000  408.084991  26580100

In [9]:
stock_data.tail()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2025-04-10,79626.140625,82700.929688,78456.132812,82565.976562,44718000633
2025-04-11,83404.835938,84247.476562,78936.320312,79625.046875,41656778779
2025-04-12,85287.109375,85856.187500,82769.375000,83404.515625,24258059104
2025-04-13,83684.976562,86015.187500,83027.007812,85279.468750,28796984817
2025-04-14,84500.000000,85310.531250,83714.000000,83714.000000,31166568448